# Generated by Django 5.1.2 on 2024-12-19 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='parking_lot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lot', to='parking.parking'),
        ),
    ]
