# Generated by Django 5.1.2 on 2024-12-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_car_parking_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='exit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
