# Generated by Django 5.1.2 on 2024-12-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_car_exit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='enter_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='exit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
